<?php
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Capsule\Manager as Capsule;

class Launchdaemons extends Migration
{
    public function up()
    {
        $capsule = new Capsule();
        $capsule::schema()->create('launchdaemons', function (Blueprint $table) {
            $table->increments('id');
            $table->string('serial_number');
            $table->string('label')->nullable();
            $table->text('path')->nullable();
            $table->boolean('disabled')->nullable();
            $table->string('username')->nullable();
            $table->string('groupname')->nullable();
            $table->text('program')->nullable();
            $table->text('programarguments')->nullable();
            $table->text('rootdirectory')->nullable();
            $table->text('workingdirectory')->nullable();
            $table->boolean('enableglobbing')->nullable();
            $table->boolean('enabletransactions')->nullable();
            $table->boolean('ondemand')->nullable();
            $table->boolean('runatload')->nullable();
            $table->integer('umask')->nullable();
            $table->integer('timeout')->nullable();
            $table->integer('exittimeout')->nullable();
            $table->integer('throttleinterval')->nullable();
            $table->boolean('initgroups')->nullable();
            $table->boolean('startonmount')->nullable();
            $table->integer('startinterval')->nullable();
            $table->text('standardinpath')->nullable();
            $table->text('standardoutpath')->nullable();
            $table->text('standarderrorpath')->nullable();
            $table->boolean('debug')->nullable();
            $table->boolean('waitfordebugger')->nullable();
            $table->integer('nice')->nullable();
            $table->string('processtype')->nullable();
            $table->boolean('abandonprocessgroup')->nullable();
            $table->boolean('lowpriorityio')->nullable();
            $table->boolean('lowprioritybackgroundio')->nullable();
            $table->boolean('enablepressuredexit')->nullable();
            $table->boolean('launchonlyonce')->nullable();
            $table->boolean('inetdcompatibility')->nullable();
            $table->boolean('sessioncreate')->nullable();
            $table->boolean('legacytimers')->nullable();
            $table->text('limitloadtosessiontype')->nullable();
            $table->text('limitloadtohosts')->nullable();
            $table->text('limitloadfromhosts')->nullable();
            $table->text('limitloadtohardware')->nullable();
            $table->text('watchpaths')->nullable();
            $table->text('queuedirectories')->nullable();
            $table->boolean('keepalive')->nullable();
            $table->boolean('networkstate')->nullable();
            $table->boolean('successfulexit')->nullable();
            $table->text('pathstate')->nullable();
            $table->text('otherjobenabled')->nullable();
            $table->text('environmentvariables')->nullable();
            $table->text('machservices')->nullable();
            $table->integer('startcalendarminute')->nullable();
            $table->integer('startcalendarhour')->nullable();
            $table->integer('startcalendarday')->nullable();
            $table->integer('startcalendarweekday')->nullable();
            $table->integer('startcalendarmonth')->nullable();
            $table->bigInteger('softresourcelimitscore')->nullable();
            $table->bigInteger('softresourcelimitscpu')->nullable();
            $table->bigInteger('softresourcelimitsdata')->nullable();
            $table->bigInteger('softresourcelimitsfilesize')->nullable();
            $table->bigInteger('softresourcelimitsmemorylock')->nullable();
            $table->bigInteger('softresourcelimitsnumberoffiles')->nullable();
            $table->bigInteger('softresourcelimitsnumberofprocesses')->nullable();
            $table->bigInteger('softresourcelimitsresidentsetsize')->nullable();
            $table->bigInteger('softresourcelimitsstack')->nullable();
            $table->bigInteger('hardresourcelimitscore')->nullable();
            $table->bigInteger('hardresourcelimitscpu')->nullable();
            $table->bigInteger('hardresourcelimitsdata')->nullable();
            $table->bigInteger('hardresourcelimitsfilesize')->nullable();
            $table->bigInteger('hardresourcelimitsmemorylock')->nullable();
            $table->bigInteger('hardresourcelimitsnumberoffiles')->nullable();
            $table->bigInteger('hardresourcelimitsnumberofprocesses')->nullable();
            $table->bigInteger('hardresourcelimitsresidentsetsize')->nullable();
            $table->bigInteger('hardresourcelimitsstack')->nullable();

            $table->index('serial_number');
            $table->index('label');
            $table->index('disabled');
            $table->index('username');
            $table->index('groupname');
            $table->index('enableglobbing');
            $table->index('enabletransactions');
            $table->index('ondemand');
            $table->index('runatload');
            $table->index('umask');
            $table->index('timeout');
            $table->index('exittimeout');
            $table->index('throttleinterval');
            $table->index('initgroups');
            $table->index('startonmount');
            $table->index('startinterval');
            $table->index('debug');
            $table->index('waitfordebugger');
            $table->index('nice');
            $table->index('processtype');
            $table->index('abandonprocessgroup');
            $table->index('lowpriorityio');
            $table->index('lowprioritybackgroundio');
            $table->index('enablepressuredexit');
            $table->index('launchonlyonce');
            $table->index('inetdcompatibility');
            $table->index('sessioncreate');
            $table->index('legacytimers');
            $table->index('keepalive');
            $table->index('networkstate');
            $table->index('successfulexit');
            $table->index('startcalendarminute');
            $table->index('startcalendarhour');
            $table->index('startcalendarday');
            $table->index('startcalendarmonth');
            $table->index('startcalendarweekday');
            $table->index('softresourcelimitscore');
            $table->index('softresourcelimitscpu');
            $table->index('softresourcelimitsdata');
            $table->index('softresourcelimitsfilesize');
            $table->index('softresourcelimitsmemorylock');
            $table->index('softresourcelimitsnumberoffiles');
            $table->index('softresourcelimitsnumberofprocesses');
            $table->index('softresourcelimitsresidentsetsize');
            $table->index('softresourcelimitsstack');
            $table->index('hardresourcelimitscore');
            $table->index('hardresourcelimitscpu');
            $table->index('hardresourcelimitsdata');
            $table->index('hardresourcelimitsfilesize');
            $table->index('hardresourcelimitsmemorylock');
            $table->index('hardresourcelimitsnumberoffiles');
            $table->index('hardresourcelimitsnumberofprocesses');
            $table->index('hardresourcelimitsresidentsetsize');
            $table->index('hardresourcelimitsstack');
        });
    }
    
    public function down()
    {
        $capsule = new Capsule();
        $capsule::schema()->dropIfExists('launchdaemons');
    }
}
