#!/bin/sh
# Check for DeployStudio updates once a day

# Seconds between checks
CHECK=86400

# Make sure the cache directory exists
DIR=$(dirname $0)
mkdir -p "$DIR/cache"


# Check if deploystudio.txt exists
if [ -e "$DIR/cache/deploystudio.txt" ]; then

	# Get current time
	TIME=$(date +%s)

	# Get file modified time
	FILEMTIME=$(stat -f "%Sm" -t "%s" "$DIR/cache/deploystudio.txt")

	# Calculate the difference in seconds
	DIFF=$(( $TIME - $FILEMTIME ))

	if [ $DIFF -gt $CHECK ]; then
		# Store date in file
		date > "$DIR/cache/deploystudio.txt"
	fi


else

	# Store date in file
	date > "$DIR/cache/deploystudio.txt"
	
fi
