#!/bin/bash

#	Check Mac OS X Server Certificate Expiry
#	by Jedda Wignall
#	http://jedda.me

# Adapted for munkireport by Arjen van Bochoven (april 2015)

CERTS=/etc/certificates/*.cert.pem
OUT="/usr/local/munki/preflight.d/cache/certificate.txt"
SEP="	" # Seperator

# Set LANG to english for the date command to work correctly
export LANG=en_EN.UTF-8

# Truncate out file
> "${OUT}"

for c in $CERTS
do
	# read the dates on each certificate
	ENDDATE=`openssl x509 -noout -in "$c" -enddate 2>/dev/null`
	SUBJECT=$(openssl x509 -noout -in "$c" -subject -nameopt oneline 2>/dev/null)
	if [ -z "$ENDDATE" ]; then
		# this cert could not be read.
  		printf "INFO - $c could not be loaded by openssl\n"
  	else
		notAfter=`echo $ENDDATE | awk -F notAfter= '{print $NF}'`
		expiryDate=$(date -j -f "%b %e %T %Y %Z" "$notAfter" "+%s")
		echo "${expiryDate}${SEP}${c}${SEP}${SUBJECT}" >> "${OUT}"
	fi
done
