version: '3'
services:
  munkireport:
    build:
      context: ./
      dockerfile: Dockerfile
    image: munkireport/munkireport-php:latest
    restart: always
    environment:
      - MODULES=applications, directory_service, disk_report, displays_info, extensions, filevault_status, homebrew, homebrew_info, ibridge, installhistory, inventory, localadmin, managedinstalls, mdm_status, munkiinfo, munkireport, munkireportinfo, network, power, printer, profile, security, softwareupdate, sophos, supported_os, timemachine, usage_stats, user_sessions, warranty, wifi
      - SITENAME=Munkireport
      - CONNECTION_DRIVER=mysql
      - CONNECTION_HOST=db
      - CONNECTION_PORT=3306
      - CONNECTION_DATABASE=munkireport
      - CONNECTION_USERNAME=munkireport
      - CONNECTION_PASSWORD=munkireport
      - AUTH_METHODS=LOCAL
      - PUID=1000
      - PGID=1000
      - CLIENT_PASSPHRASES=
      - APP_URL=https://localhost
      - TZ=Europe/Berlin
    depends_on:
      - db
    ports:
      - 8080:8080  # You should avoid privileged ports, here and in kubernetes
    volumes:
      - ./munkireport-db/:/var/munkireport/app/db
      - ./user//:/var/munkireport/local/users
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=munkireport
      - MARIADB_USER=munkireport
      - MARIADB_PASSWORD=munkireport
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./db/:/var/lib/mysql
