version: '3'
services:
  munkireport:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ghcr.io/munkireport/munkireport-php:wip
    restart: always
    environment:
      - MODULES=applications, directory_service, disk_report, displays_info, extensions, filevault_status, homebrew, homebrew_info, ibridge, installhistory, inventory, localadmin, managedinstalls, mdm_status, munkiinfo, munkireport, munkireportinfo, network, power, printer, profile, security, softwareupdate, sophos, supported_os, timemachine, usage_stats, user_sessions, warranty, wifi
      - SITENAME=Munkireport
      # Old-style (MunkiReport v5) Database Config
#      - CONNECTION_DRIVER=mysql
#      - CONNECTION_HOST=mariadb
#      - CONNECTION_PORT=3306
#      - CONNECTION_DATABASE=munkireport
#      - CONNECTION_USERNAME=munkireport
#      - CONNECTION_PASSWORD=munkireport

      # New-style (Laravel) Database Config
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_USERNAME=munkireport
      - DB_PASSWORD=munkireport
      - DB_DATABASE=munkireport
      - AUTH_METHODS=LOCAL
      - PUID=1000
      - PGID=1000
      - CLIENT_PASSPHRASES=
      - APP_URL=http://localhost:8080
      - TZ=Europe/Berlin
    depends_on:
      - mariadb
    ports:
      - 8080:8080  # You should avoid privileged ports, here and in kubernetes
    volumes:
      - ./munkireport-db/:/var/munkireport/app/db
      - ./user//:/var/munkireport/local/users
  mariadb:
    image: mariadb:10.10
    restart: always
    environment:
      - MARIADB_DATABASE=munkireport
      - MARIADB_USER=munkireport
      - MARIADB_PASSWORD=munkireport
      - MARIADB_ROOT_PASSWORD=munkireport
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
