#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;


require_once __DIR__ . '/app/helpers/env_helper.php';
require_once __DIR__ . '/app/helpers/site_helper.php';
require_once __DIR__.'/vendor/autoload.php';

define('PUBLIC_ROOT', dirname(__FILE__) . '/public' );
define('APP_ROOT', dirname(__FILE__) . '/' );

spl_autoload_register('munkireport_autoload');

require_once APP_ROOT . 'app/helpers/config_helper.php';
initDotEnv();
initConfig();
configAppendFile(APP_ROOT . 'app/config/app.php');
configAppendFile(APP_ROOT . 'app/config/db.php', 'connection');

$container = new Container;
$dispatcher = new Dispatcher;
$version = "MunkiReport"; // Laravel version

$app = new Application($container, $dispatcher, $version);

$app->setCatchExceptions(true);

$app->add(new App\Console\Commands\MigrateCommand);
$app->add(new App\Console\Commands\ModuleCommand);
$app->add(new App\Console\Commands\MigrationCommand);
$app->add(new App\Console\Commands\SeedCommand);
$app->add(new App\Console\Commands\UpCommand);
$app->add(new App\Console\Commands\DownCommand);

$app->run();