#!/bin/bash

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# OS check
OSVERSION=$(/usr/bin/sw_vers -productVersion | /usr/bin/cut -d . -f 2)

if [[ ${OSVERSION} -lt 8 ]]; then

    echo "Error: Caching module is only supported on 10.8 or higher"
    exit

else

if [ ! -f /Library/Server/Caching/Logs/Metrics.sqlite ]; then
    echo "Error: Caching metrics database not found! Is caching turned on?"

else
    /usr/bin/sqlite3 /Library/Server/Caching/Logs/Metrics.sqlite "SELECT * FROM statsData;" > /usr/local/munki/preflight.d/cache/caching.txt
fi

fi
