#!/usr/bin/python
"""
Adds Internet Plug-Ins to the Application Inventory data that is gathered
by munki.
Thanks to Adam Reed and Josh Malone
"""
import os
import sys
import CoreFoundation
sys.path.insert(0, '/usr/local/munki')

from munkilib import FoundationPlist

# check the ManagedInstalls plist for where the ManagedInstallDir is located
munki_install_dir = CoreFoundation.CFPreferencesCopyAppValue("ManagedInstallDir", "ManagedInstalls")
if munki_install_dir:
    invPath = os.path.join(munki_install_dir, 'ApplicationInventory.plist')
else:
    invPath = '/Library/Managed Installs/ApplicationInventory.plist'

# Look for our set path to make sure it exists. If not exit because munki
# most likely isn't installed yet
try:
    appinv = FoundationPlist.readPlist(invPath)
except FoundationPlist.NSPropertyListSerializationException as e:
    print "{0} couldn't be found. Exiting...".format(invPath)
    exit(1)

plugins = r"/Library/Internet Plug-Ins/"
directoryListing = os.listdir(plugins)

print "Adding %i plugins" % len(directoryListing)

for x in directoryListing:
    path = os.path.join(plugins, x, 'Contents/Info.plist')
    try:
        info = FoundationPlist.readPlist(path)
        plugin = {}
        plugin['CFBundleName'] = info.get('CFBundleName', x)
        plugin['bundleid'] = info.get('CFBundleIdentifier', 'N/A')
        plugin['version'] = info.get('CFBundleVersion', 'N/A')
        plugin['path'] = os.path.join(plugins, x)
        plugin['name'] = info.get('CFBundleName', os.path.splitext(os.path.basename(x))[0])
        appinv.append(plugin.copy())
    except Exception, message:
        pass

FoundationPlist.writePlist(appinv, invPath)
exit(0)