<?php
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Capsule\Manager as Capsule;

class FanTemps extends Migration
{
    private $tableName = 'fan_temps';
    private $tableNameV2 = 'fan_temps_orig';

    public function up()
    {
        $capsule = new Capsule();
        $migrateData = false;

        if ($capsule::schema()->hasTable($this->tableNameV2)) {
            // Migration already failed before, but didnt finish
            throw new Exception("previous failed migration exists");
        }

        if ($capsule::schema()->hasTable($this->tableName)) {
            $capsule::schema()->rename($this->tableName, $this->tableNameV2);
            $migrateData = true;
        }


        $capsule::schema()->create($this->tableName, function (Blueprint $table) {
            $table->increments('id');
            $table->string('serial_number')->nullable();

            $table->integer('fan_0')->nullable();
            $table->integer('fan_1')->nullable();
            $table->integer('fan_2')->nullable();
            $table->integer('fan_3')->nullable();
            $table->integer('fan_4')->nullable();
            $table->integer('fan_5')->nullable();
            $table->integer('fan_6')->nullable();
            $table->integer('fan_7')->nullable();
            $table->integer('fan_8')->nullable();
            $table->integer('fanmin0')->nullable();
            $table->integer('fanmin1')->nullable();
            $table->integer('fanmin2')->nullable();
            $table->integer('fanmin3')->nullable();
            $table->integer('fanmin4')->nullable();
            $table->integer('fanmin5')->nullable();
            $table->integer('fanmin6')->nullable();
            $table->integer('fanmin7')->nullable();
            $table->integer('fanmin8')->nullable();
            $table->integer('fanmax0')->nullable();
            $table->integer('fanmax1')->nullable();
            $table->integer('fanmax2')->nullable();
            $table->integer('fanmax3')->nullable();
            $table->integer('fanmax4')->nullable();
            $table->integer('fanmax5')->nullable();
            $table->integer('fanmax6')->nullable();
            $table->integer('fanmax7')->nullable();
            $table->integer('fanmax8')->nullable();
            $table->string('fanlabel0')->nullable();
            $table->string('fanlabel1')->nullable();
            $table->string('fanlabel2')->nullable();
            $table->string('fanlabel3')->nullable();
            $table->string('fanlabel4')->nullable();
            $table->string('fanlabel5')->nullable();
            $table->string('fanlabel6')->nullable();
            $table->string('fanlabel7')->nullable();
            $table->string('fanlabel8')->nullable();
            $table->string('discin')->nullable();
            // Keep these mostly alphabetized to properly order client tab
            $table->float('ta0p')->nullable();
            $table->float('ta1p')->nullable();
            $table->float('ta2p')->nullable();
            $table->float('ta0p2')->nullable();
            $table->float('ta1p2')->nullable();
            $table->float('ta0g')->nullable();
            $table->float('ta2g')->nullable();
            $table->float('ta0s')->nullable();
            $table->float('ta1s')->nullable();
            $table->float('ta2s')->nullable();
            $table->float('ta3s')->nullable();
            $table->float('ta4s')->nullable();
            $table->float('ta5s')->nullable();
            $table->float('talc')->nullable();
            $table->float('tarc')->nullable();
            $table->float('tb0p')->nullable();
            $table->float('tb0t')->nullable();
            $table->float('tb1t')->nullable();
            $table->float('tb2t')->nullable();
            $table->float('tb3t')->nullable();
            $table->float('tbxt')->nullable();
            $table->float('tc0c')->nullable();
            $table->float('tc0d')->nullable();
            $table->float('tc0d2')->nullable();
            $table->float('tc0e')->nullable();
            $table->float('tc0f')->nullable();
            $table->float('tc0g')->nullable();
            $table->float('tc0h')->nullable();
            $table->float('tc0j')->nullable();
            $table->float('tc0p')->nullable();
            $table->float('tc0p2')->nullable();
            $table->float('tc1c')->nullable();
            $table->float('tc1d')->nullable();
            $table->float('tc1e')->nullable();
            $table->float('tc1f')->nullable();
            $table->float('tc1h')->nullable();
            $table->float('tc1p')->nullable();
            $table->float('tc2c')->nullable();
            $table->float('tc2p')->nullable();
            $table->float('tc3c')->nullable();
            $table->float('tc3p')->nullable();
            $table->float('tc4c')->nullable();
            $table->float('tc5c')->nullable();
            $table->float('tc6c')->nullable();
            $table->float('tc7c')->nullable();
            $table->float('tc8c')->nullable();
            $table->float('tc0c2')->nullable();
            $table->float('tc1c2')->nullable();
            $table->float('tc2c2')->nullable();
            $table->float('tc3c2')->nullable();
            $table->float('tc2d')->nullable();
            $table->float('tcac')->nullable();
            $table->float('tcad')->nullable();
            $table->float('tcag')->nullable();
            $table->float('tcah')->nullable();
            $table->float('tcas')->nullable();
            $table->float('tcbc')->nullable();
            $table->float('tcbd')->nullable();
            $table->float('tcbg')->nullable();
            $table->float('tcbh')->nullable();
            $table->float('tcbs')->nullable();
            $table->float('tcfp')->nullable();
            $table->float('tcgc')->nullable();
            $table->float('tcgc2')->nullable();
            $table->float('tchp')->nullable();
            $table->float('tcpg')->nullable();
            $table->float('tcsa')->nullable();
            $table->float('tcsc')->nullable();
            $table->float('tcsc2')->nullable();
            $table->float('tctd')->nullable();
            $table->float('tcxc')->nullable();
            $table->float('tcxc2')->nullable();
            $table->float('tcsr')->nullable();
            $table->float('te0t')->nullable();
            $table->float('te1f')->nullable();
            $table->float('te1p')->nullable();
            $table->float('te1s')->nullable();
            $table->float('te2f')->nullable();
            $table->float('te2s')->nullable();
            $table->float('te3f')->nullable();
            $table->float('te3s')->nullable();
            $table->float('te4f')->nullable();
            $table->float('te4s')->nullable();
            $table->float('te5f')->nullable();
            $table->float('te5s')->nullable();
            $table->float('tegg')->nullable();
            $table->float('tegp')->nullable();
            $table->float('terg')->nullable();
            $table->float('tetp')->nullable();
            $table->float('tg0d')->nullable();
            $table->float('tg0g')->nullable();
            $table->float('tg0h')->nullable();
            $table->float('tg0p')->nullable();
            $table->float('tg0p2')->nullable();
            $table->float('tg0r')->nullable();
            $table->float('tg0t')->nullable();
            $table->float('tg1d')->nullable();
            $table->float('tg1f')->nullable();
            $table->float('tg1h')->nullable();
            $table->float('tg1d2')->nullable();
            $table->float('tg1p')->nullable();
            $table->float('tg1r')->nullable();
            $table->float('tgtc')->nullable();
            $table->float('tgtd')->nullable();
            $table->float('tgvp')->nullable();
            $table->float('th0a')->nullable();
            $table->float('th0a2')->nullable();
            $table->float('th0b')->nullable();
            $table->float('th0b2')->nullable();
            $table->float('th0c')->nullable();
            $table->float('th0c2')->nullable();
            $table->float('th0f')->nullable();
            $table->float('th0h')->nullable();
            $table->float('th0o')->nullable();
            $table->float('th0p')->nullable();
            $table->float('th0r')->nullable();
            $table->float('th0v')->nullable();
            $table->float('th0x')->nullable();
            $table->float('th0x2')->nullable();
            $table->float('th1a')->nullable();
            $table->float('th1a2')->nullable();
            $table->float('th1b')->nullable();
            $table->float('th1b2')->nullable();
            $table->float('th1c')->nullable();
            $table->float('th1c2')->nullable();
            $table->float('th1f')->nullable();
            $table->float('th1g')->nullable();
            $table->float('th1h')->nullable();
            $table->float('th1o')->nullable();
            $table->float('th1p')->nullable();
            $table->float('th1r')->nullable();
            $table->float('th1v')->nullable();
            $table->float('th1x')->nullable();
            $table->float('th2f')->nullable();
            $table->float('th2g')->nullable();
            $table->float('th2h')->nullable();
            $table->float('th2p')->nullable();
            $table->float('th2v')->nullable();
            $table->float('th3f')->nullable();
            $table->float('th3g')->nullable();
            $table->float('th3p')->nullable();
            $table->float('th3c')->nullable();
            $table->float('th4f')->nullable();
            $table->float('th4p')->nullable();
            $table->float('th4v')->nullable();
            $table->float('thps')->nullable();
            $table->float('thsp')->nullable();
            $table->float('thtg')->nullable();
            $table->float('ti0p')->nullable();
            $table->float('ti0p2')->nullable();
            $table->float('ti1p')->nullable();
            $table->float('ti1p2')->nullable();
            $table->float('tl0p')->nullable();
            $table->float('tl0p2')->nullable();
            $table->float('tl0v')->nullable();
            $table->float('tl1v')->nullable();
            $table->float('tl1p')->nullable();
            $table->float('tl2v')->nullable();
            $table->float('tlav')->nullable();
            $table->float('tlbv')->nullable();
            $table->float('tlcv')->nullable();
            $table->float('tm0s')->nullable();
            $table->float('tm0p')->nullable();
            $table->float('tm0p2')->nullable();
            $table->float('tm0p3')->nullable();
            $table->float('tm0p4')->nullable();
            $table->float('tm0r')->nullable();
            $table->float('tm1p')->nullable();
            $table->float('tm1r')->nullable();
            $table->float('tm2p')->nullable();
            $table->float('tm3p')->nullable();
            $table->float('tm4p')->nullable();
            $table->float('tm5p')->nullable();
            $table->float('tm6p')->nullable();
            $table->float('tm7p')->nullable();
            $table->float('tm8p')->nullable();
            $table->float('tm9p')->nullable();
            $table->float('tm1s')->nullable();
            $table->float('tm2s')->nullable();
            $table->float('tm3s')->nullable();
            $table->float('tm4s')->nullable();
            $table->float('tm5s')->nullable();
            $table->float('tm6s')->nullable();
            $table->float('tm7s')->nullable();
            $table->float('tm8s')->nullable();
            $table->float('tm9s')->nullable();
            $table->float('tmas')->nullable();
            $table->float('tmbs')->nullable();
            $table->float('tmcs')->nullable();
            $table->float('tma1')->nullable();
            $table->float('tma2')->nullable();
            $table->float('tma3')->nullable();
            $table->float('tma4')->nullable();
            $table->float('tmap')->nullable();
            $table->float('tmb1')->nullable();
            $table->float('tmb2')->nullable();
            $table->float('tmb3')->nullable();
            $table->float('tmb4')->nullable();
            $table->float('tmhs')->nullable();
            $table->float('tmlb')->nullable();
            $table->float('tmls')->nullable();
            $table->float('tmps')->nullable();
            $table->float('tmpv')->nullable();
            $table->float('tmtg')->nullable();
            $table->float('tn0c')->nullable();
            $table->float('tn0d')->nullable();
            $table->float('tn0h')->nullable();
            $table->float('th0n')->nullable();
            $table->float('tn0p')->nullable();
            $table->float('tn1p')->nullable();
            $table->float('tnfp')->nullable();
            $table->float('tntg')->nullable();
            $table->float('to0p')->nullable();
            $table->float('tp0c')->nullable();
            $table->float('tp0d')->nullable();
            $table->float('tp0p')->nullable();
            $table->float('tp0p2')->nullable();
            $table->float('tp0t')->nullable();
            $table->float('tp0g')->nullable();
            $table->float('tp1c')->nullable();
            $table->float('tp1g')->nullable();
            $table->float('tp1p')->nullable();
            $table->float('tp2g')->nullable();
            $table->float('tp2h')->nullable();
            $table->float('tp2p')->nullable();
            $table->float('tp3h')->nullable();
            $table->float('tp3p')->nullable();
            $table->float('tp3v')->nullable();
            $table->float('tp4p')->nullable();
            $table->float('tp5p')->nullable();
            $table->float('tpcd')->nullable();
            $table->float('tpps')->nullable();
            $table->float('tptg')->nullable();
            $table->float('ts0c')->nullable();
            $table->float('ts0g')->nullable();
            $table->float('ts0s')->nullable();
            $table->float('ts0p')->nullable();
            $table->float('ts0v')->nullable();
            $table->float('ts1p')->nullable();
            $table->float('ts1s')->nullable();
            $table->float('ts2p')->nullable();
            $table->float('ts2s')->nullable();
            $table->float('ts2v')->nullable();
            $table->float('ttf0')->nullable();
            $table->float('ttld')->nullable();
            $table->float('ttrd')->nullable();
            $table->float('tw0p')->nullable();
            $table->float('tw0p2')->nullable();

            $table->index('serial_number');
            $table->index('ta0p');
            $table->index('tc0f');
            $table->index('tc0d');
            $table->index('tc0p');
            $table->index('tb0t');
            $table->index('tb1t');
            $table->index('tb2t');
            $table->index('tg0d');
            $table->index('tg0h');
            $table->index('tg0p');
            $table->index('th0p');
            $table->index('th0h');
            $table->index('th1h');
            $table->index('th2h');
            $table->index('tm0s');
            $table->index('tm0p');
            $table->index('ts0p');
            $table->index('tl0p');
            $table->index('tm0p4');
            $table->index('tn0h');
            $table->index('tn0d');
            $table->index('tn0p');
            $table->index('tp0p');
            $table->index('discin');
            $table->index('fan_0');
            $table->index('fan_1');
            $table->index('fan_2');
            $table->index('fan_3');
            $table->index('fan_4');
            $table->index('fan_5');
            $table->index('fan_6');
            $table->index('fan_7');
            $table->index('fan_8');
            $table->index('fanmin0');
            $table->index('fanmin1');
            $table->index('fanmin2');
            $table->index('fanmin3');
            $table->index('fanmin4');
            $table->index('fanmin5');
            $table->index('fanmin6');
            $table->index('fanmin7');
            $table->index('fanmin8');
            $table->index('fanmax0');
            $table->index('fanmax1');
            $table->index('fanmax2');
            $table->index('fanmax3');
            $table->index('fanmax4');
            $table->index('fanmax5');
            $table->index('fanmax6');
            $table->index('fanmax7');
            $table->index('fanmax8');
            $table->index('fanlabel0');
            $table->index('fanlabel1');
            $table->index('fanlabel2');
            $table->index('fanlabel3');
            $table->index('fanlabel4');
            $table->index('fanlabel5');
            $table->index('fanlabel6');
            $table->index('fanlabel7');
            $table->index('fanlabel8');
        });
        
        if ($migrateData) {
            $capsule::unprepared("INSERT INTO 
                $this->tableName
            SELECT
                id,
                serial_number,
                fan_0,
                fan_1,
                fan_2,
                fan_3,
                fan_4,
                fan_5,
                fan_6,
                fan_7,
                fan_8,
                fanmin0,
                fanmin1,
                fanmin2,
                fanmin3,
                fanmin4,
                fanmin5,
                fanmin6,
                fanmin7,
                fanmin8,
                fanmax0,
                fanmax1,
                fanmax2,
                fanmax3,
                fanmax4,
                fanmax5,
                fanmax6,
                fanmax7,
                fanmax8,
                fanlabel0,
                fanlabel1,
                fanlabel2,
                fanlabel3,
                fanlabel4,
                fanlabel5,
                fanlabel6,
                fanlabel7,
                fanlabel8,
                discin,
                ta0p,
                ta1p,
                ta2p,
                ta0p2,
                ta1p2,
                ta0g,
                ta2g,
                ta0s,
                ta1s,
                ta2s,
                ta3s,
                ta4s,
                ta5s,
                talc,
                tarc,
                tb0p,
                tb0t,
                tb1t,
                tb2t,
                tb3t,
                tbxt,
                tc0c,
                tc0d,
                tc0d2,
                tc0e,
                tc0f,
                tc0g,
                tc0h,
                tc0j,
                tc0p,
                tc0p2,
                tc1c,
                tc1d,
                tc1e,
                tc1f,
                tc1h,
                tc1p,
                tc2c,
                tc2p,
                tc3c,
                tc3p,
                tc4c,
                tc5c,
                tc6c,
                tc7c,
                tc8c,
                tc0c2,
                tc1c2,
                tc2c2,
                tc3c2,
                tc2d,
                tcac,
                tcad,
                tcag,
                tcah,
                tcas,
                tcbc,
                tcbd,
                tcbg,
                tcbh,
                tcbs,
                tcfp,
                tcgc,
                tcgc2,
                tchp,
                tcpg,
                tcsa,
                tcsc,
                tcsc2,
                tctd,
                tcxc,
                tcxc2,
                tcsr,
                te0t,
                te1f,
                te1p,
                te1s,
                te2f,
                te2s,
                te3f,
                te3s,
                te4f,
                te4s,
                te5f,
                te5s,
                tegg,
                tegp,
                terg,
                tetp,
                tg0d,
                tg0g,
                tg0h,
                tg0p,
                tg0p2,
                tg0r,
                tg0t,
                tg1d,
                tg1f,
                tg1h,
                tg1d2,
                tg1p,
                tg1r,
                tgtc,
                tgtd,
                tgvp,
                th0a,
                th0a2,
                th0b,
                th0b2,
                th0c,
                th0c2,
                th0f,
                th0h,
                th0o,
                th0p,
                th0r,
                th0v,
                th0x,
                th0x2,
                th1a,
                th1a2,
                th1b,
                th1b2,
                th1c,
                th1c2,
                th1f,
                th1g,
                th1h,
                th1o,
                th1p,
                th1r,
                th1v,
                th1x,
                th2f,
                th2g,
                th2h,
                th2p,
                th2v,
                th3f,
                th3g,
                th3p,
                th3c,
                th4f,
                th4p,
                th4v,
                thps,
                thsp,
                thtg,
                ti0p,
                ti0p2,
                ti1p,
                ti1p2,
                tl0p,
                tl0p2,
                tl0v,
                tl1v,
                tl1p,
                tl2v,
                tlav,
                tlbv,
                tlcv,
                tm0s,
                tm0p,
                tm0p2,
                tm0p3,
                tm0p4,
                tm0r,
                tm1p,
                tm1r,
                tm2p,
                tm3p,
                tm4p,
                tm5p,
                tm6p,
                tm7p,
                tm8p,
                tm9p,
                tm1s,
                tm2s,
                tm3s,
                tm4s,
                tm5s,
                tm6s,
                tm7s,
                tm8s,
                tm9s,
                tmas,
                tmbs,
                tmcs,
                tma1,
                tma2,
                tma3,
                tma4,
                tmap,
                tmb1,
                tmb2,
                tmb3,
                tmb4,
                tmhs,
                tmlb,
                tmls,
                tmps,
                tmpv,
                tmtg,
                tn0c,
                tn0d,
                tn0h,
                th0n,
                tn0p,
                tn1p,
                tnfp,
                tntg,
                to0p,
                tp0c,
                tp0d,
                tp0p,
                tp0p2,
                tp0t,
                tp0g,
                tp1c,
                tp1g,
                tp1p,
                tp2g,
                tp2h,
                tp2p,
                tp3h,
                tp3p,
                tp3v,
                tp4p,
                tp5p,
                tpcd,
                tpps,
                tptg,
                ts0c,
                ts0g,
                ts0s,
                ts0p,
                ts0v,
                ts1p,
                ts1s,
                ts2p,
                ts2s,
                ts2v,
                ttf0,
                ttld,
                ttrd,
                tw0p,
                tw0p2
            FROM
                $this->tableNameV2");
        }
    }
    
    public function down()
    {
        $capsule = new Capsule();
        $capsule::schema()->dropIfExists($this->tableName);
        if ($capsule::schema()->hasTable($this->tableNameV2)) {
            $capsule::schema()->rename($this->tableNameV2, $this->tableName);
        }
    }
}
