<?php

namespace Tests\Feature;

use App\Http\Controllers\DatatablesController;
use App\Machine;
use App\ReportData;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\AuthorizationTestCase;
use Tests\TestCase;

class DatatablesControllerTest extends AuthorizationTestCase
{
    use RefreshDatabase;

    protected $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->reportdata = ReportData::factory()->create();
        $this->machine = Machine::factory()->create(['serial_number' => $this->reportdata->serial_number]);
    }

    protected function tearDown(): void
    {
        $this->reportdata = null;
        $this->machine = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testArdData()
    {
        $response = $this->actingAs($this->user)
            ->post('/datatables/data', [
                'draw' => '1',
                'columns' => [
                    [
                        'data' => '0',
                        'name' => 'machine.computer_name',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '1',
                        'name' => 'reportdata.serial_number',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '2',
                        'name' => 'reportdata.long_username',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '3',
                        'name' => 'ard.text1',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '4',
                        'name' => 'ard.text2',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '5',
                        'name' => 'ard.text3',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '6',
                        'name' => 'ard.text4',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '7',
                        'name' => 'ard.admin_machines',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                    [
                        'data' => '8',
                        'name' => 'security.ard_users',
                        'searachable' => 'true',
                        'orderable' => 'true',
                        'search' => [
                            'value' => '',
                            'regex' => 'false',
                        ],
                    ],
                ],
                'start' => '0',
                'length' => '10',
                'search' => [
                    'value' => '',
                    'regex' => 'false',
                ]
            ]);

        $response->assertJsonStructure([
            'draw',
            'data',
            'recordsTotal',
            'recordsFiltered',
        ]);
    }
}
