<?php

namespace Tests\Feature;

use App\Http\Controllers\ShowController;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;


class ShowControllerTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->user = factory(User::class)->create();
    }

    protected function tearDown(): void
    {
        $this->user = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
    
    public function testReport()
    {

    }

    public function testDashboardRedirect()
    {
        $this->actingAs($this->user)
            ->get('/show/dashboard')
            ->assertRedirect('/show/dashboard/default');
    }

    public function testDashboardNotFound()
    {
        $this->actingAs($this->user)
            ->get('/show/dashboard/abcxyz')
            ->assertNotFound();
    }

    public function testCustom()
    {

    }

    public function testIndex()
    {
        $this->actingAs($this->user)
            ->get('/show')
            ->assertRedirect('/show/dashboard/default');
    }

    public function testListing()
    {
        $this->markTestIncomplete();
//        $this->actingAs($this->user)
//            ->get('/show/listing')
//            ->assertRedirect('/show/dashboard/default');
    }
}
