<?php

namespace Tests\Feature;

use App\Http\Controllers\SystemController;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class SystemControllerTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->user = factory(User::class)->create();
    }

    protected function tearDown(): void
    {
        $this->user = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetDataBaseInfo()
    {
        $response = $this->actingAs($this->user)
            ->get('/system/DataBaseInfo');

        $response->assertHeader('Content-Type', 'application/json');
        $response->assertOk()
            ->assertJsonStructure([
                'db.driver',
                'db.connectable',
                'db.writable',
                'db.size',
                'error',
                'version']);
    }

    public function testGetPhpInfo()
    {
        $response = $this->actingAs($this->user)
            ->get('/system/phpInfo');

        $response->assertHeader('Content-Type', 'application/json');
        $response->assertOk();
        $this->assertNotNull($response->jsonGet('phpinfo')); // Too many keys to test really.
    }

    public function testShow()
    {
        $response = $this->actingAs($this->user)
            ->get('/system/show/status');
        $response->assertOk();
    }

    public function testShowNotFound()
    {
        $response = $this->actingAs($this->user)
            ->get('/system/show/xyzabc');
        $response->assertNotFound();
    }
}
