#!/bin/bash

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# Create cache dir if it does not exist
DIR=$(dirname $0)
mkdir -p "$DIR/cache"
wifi_file="$DIR/cache/wifi.txt"

hw_check=`networksetup -listallhardwareports | grep -E '(Wi-Fi|AirPort)' -A 1`
if [[ "$hw_check" != "" ]] ; then

wifi_data=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I`

if [[ "${wifi_data}" == *"AirPort: Off"* ]] || [[ "${wifi_data}" == *"AirPort is Off"* ]] ; then

echo "     agrCtlRSSI: 0" > $wifi_file
echo "     agrExtRSSI: 0" >> $wifi_file
echo "    agrCtlNoise: 0" >> $wifi_file
echo "    agrExtNoise: 0" >> $wifi_file
echo "          state: off" >> $wifi_file
echo "        op mode: " >> $wifi_file
echo "     lastTxRate: 0" >> $wifi_file
echo "        maxRate: 0" >> $wifi_file
echo "lastAssocStatus: " >> $wifi_file
echo "    802.11 auth: " >> $wifi_file
echo "      link auth: " >> $wifi_file
echo "          BSSID: " >> $wifi_file
echo "           SSID: " >> $wifi_file
echo "            MCS: 0" >> $wifi_file
echo "        channel: " >> $wifi_file
date +%s >> $wifi_file

elif [[ "${wifi_data}" == "" ]] ; then

# Check if Internet Connection Sharing is turned on
check_ICS=`/usr/libexec/PlistBuddy /Library/Preferences/SystemConfiguration/com.apple.nat.plist -c 'Print :NAT:SharingDevices:0'`
if [[ "${check_ICS}" == "en"* ]] ; then

echo "     agrCtlRSSI: 0" > $wifi_file
echo "     agrExtRSSI: 0" >> $wifi_file
echo "    agrCtlNoise: 0" >> $wifi_file
echo "    agrExtNoise: 0" >> $wifi_file
echo "          state: sharing" >> $wifi_file
echo "        op mode: " >> $wifi_file
echo "     lastTxRate: 0" >> $wifi_file
echo "        maxRate: 0" >> $wifi_file
echo "lastAssocStatus: " >> $wifi_file
echo "    802.11 auth: " >> $wifi_file
echo "      link auth: " >> $wifi_file
echo "          BSSID: " >> $wifi_file
echo "           SSID: " >> $wifi_file
echo "            MCS: 0" >> $wifi_file
echo "        channel: " >> $wifi_file
date +%s >> $wifi_file

else

echo "     agrCtlRSSI: 0" > $wifi_file
echo "     agrExtRSSI: 0" >> $wifi_file
echo "    agrCtlNoise: 0" >> $wifi_file
echo "    agrExtNoise: 0" >> $wifi_file
echo "          state: unknown" >> $wifi_file
echo "        op mode: " >> $wifi_file
echo "     lastTxRate: 0" >> $wifi_file
echo "        maxRate: 0" >> $wifi_file
echo "lastAssocStatus: " >> $wifi_file
echo "    802.11 auth: " >> $wifi_file
echo "      link auth: " >> $wifi_file
echo "          BSSID: " >> $wifi_file
echo "           SSID: " >> $wifi_file
echo "            MCS: 0" >> $wifi_file
echo "        channel: " >> $wifi_file
date +%s >> $wifi_file

fi

else
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I > $wifi_file
fi

else
echo "     agrCtlRSSI: 0" > $wifi_file
echo "     agrExtRSSI: 0" >> $wifi_file
echo "    agrCtlNoise: 0" >> $wifi_file
echo "    agrExtNoise: 0" >> $wifi_file
echo "          state: no wifi" >> $wifi_file
echo "        op mode: " >> $wifi_file
echo "     lastTxRate: 0" >> $wifi_file
echo "        maxRate: 0" >> $wifi_file
echo "lastAssocStatus: " >> $wifi_file
echo "    802.11 auth: " >> $wifi_file
echo "      link auth: " >> $wifi_file
echo "          BSSID: " >> $wifi_file
echo "           SSID: " >> $wifi_file
echo "            MCS: 0" >> $wifi_file
echo "        channel: " >> $wifi_file
date +%s >> $wifi_file
fi
