#!/bin/bash

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# OS check
OSVERSION=$(/usr/bin/sw_vers -productVersion | /usr/bin/cut -d . -f 2)

# Serveradmin executable
if [[ ${OSVERSION} -lt 8 ]]; then
    SERVERADMIN="/usr/sbin/serveradmin"
else
    SERVERADMIN="/Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin"
fi

# Out file
OUT="/usr/local/munki/preflight.d/cache/services.txt"

# List of services to check
SERVICES="addressbook afp caching calendar \
certs collabd devicemgr dhcp dirserv dns ftp \
history jabber mail netboot network nfs radius \
san smb swupdate timemachine vpn web wiki xcode"

 
# Truncate out file
> "$OUT"

# Check if serveradmin exists
if [ ! -e "$SERVERADMIN" ]; then
	echo "$SERVERADMIN not found, aborting"
	exit
fi


for i in $SERVICES
	do "$SERVERADMIN" status $i | grep '.*:state =' >> $OUT
done