#!/bin/bash

# Serveradmin executable
SERVERADMIN="/Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin"

# Out file
OUT="/usr/local/munki/preflight.d/cache/services.txt"

# List of services to check
SERVICES="addressbook afp caching calendar \
certs collabd devicemgr dhcp dirserv dns ftp \
history jabber mail netboot network nfs radius \
san smb swupdate timemachine vpn web wiki xcode"

 
# Truncate out file
> "$OUT"

# Check if serveradmin exists
if [ -z $( /bin/launchctl list com.apple.serverd 2>/dev/null ) ]; then
	# Just exit here if com.apple.serverd is not running
	exit
fi


for i in $SERVICES
	do "$SERVERADMIN" status $i | grep '.*:state =' >> $OUT
done