#!/bin/bash

if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# Create cache dir if it does not exist
DIR=$(dirname $0)
mkdir -p "$DIR/cache"

echo 'Get filevault status'

# Store filevault status in filevaultstatus.txt
/usr/local/bin/filevault_2_status_check.sh > "$DIR/cache/filevaultstatus.txt"