<?php

class Migration_fan_temps_add_columns extends \Model
{
    protected $new_columns = array(
        'fnfd' => 'INT(11)',
        'fnum' => 'INT(11)',
        'mssf' => 'INT(11)',
        'dba0' => 'float',
        'dba1' => 'float',
        'dba2' => 'float',
        'dbah' => 'float',
        'dbat' => 'float',
        'aupo' => 'INT(11)',
        'alsl' => 'INT(11)',
        'msac' => 'INT(11)',
        'msag' => 'float',
        'msam' => 'float',
        'msha' => 'float',
        'msld' => 'INT(11)',
        'hdbs' => 'INT(11)',
        'mssd' => 'INT(11)',
        'mssp' => 'INT(11)',
        'mstc' => 'INT(11)',
        'mstg' => 'INT(11)',
        'mstm' => 'INT(11)',
        'bnum' => 'INT(11)',
        'natj' => 'INT(11)',
        'nati' => 'INT(11)',
        'lsof' => 'INT(11)',
        'lspv' => 'VARCHAR(255)',
        'mo_x' => 'float',
        'mo_y' => 'float',
        'mo_z' => 'float',
        'spht' => 'INT(11)',
        'sph0' => 'INT(11)',
        'sght' => 'INT(11)',
        'sgtt' => 'float',
        'sctg' => 'float',
        'sgtg' => 'float',
        'shtg' => 'float',
        'sltg' => 'float',
        'sltp' => 'float',
        'sotg' => 'float',
        'sptg' => 'float',
        'slpt' => 'float',
        'slst' => 'float',
        'sppt' => 'float',
        'spst' => 'float',
        'ibac' => 'float',
        'ib0p' => 'float',
        'ib0l' => 'float',
        'ib0r' => 'float',
        'ipbf' => 'float',
        'icmc' => 'float',
        'ipbr' => 'float',
        'icac' => 'float',
        'icbc' => 'float',
        'ics0' => 'float',
        'ic0c' => 'float',
        'ic1c' => 'float',
        'ic2c' => 'float',
        'ic3c' => 'float',
        'ic4c' => 'float',
        'ic5c' => 'float',
        'ic6c' => 'float',
        'ic7c' => 'float',
        'ic3c' => 'float',
        'ic5r' => 'float',
        'ic0g' => 'float',
        'icgc' => 'float',
        'icgm' => 'float',
        'icam' => 'float',
        'ics1' => 'float',
        'imcc' => 'float',
        'ic0m' => 'float',
        'ic8r' => 'float',
        'ic0r' => 'float',
        'icec' => 'float',
        'icsc' => 'float',
        'im3c' => 'float',
        'ig0r' => 'float',
        'ig0c' => 'float',
        'ig1c' => 'float',
        'ig0f' => 'float',
        'ih1z' => 'float',
        'ih2z' => 'float',
        'ih3z' => 'float',
        'ih4z' => 'float',
        'ih05' => 'float',
        'ih02' => 'float',
        'ikbc' => 'float',
        'ilcd' => 'float',
        'iblc' => 'float',
        'iblr' => 'float',
        'im1c' => 'float',
        'i18c' => 'float',
        'id2r' => 'float',
        'id0r' => 'float',
        'id5r' => 'float',
        'im0r' => 'float',
        'im0c' => 'float',
        'imas' => 'float',
        'imbs' => 'float',
        'io0r' => 'float',
        'io3r' => 'float',
        'io5r' => 'float',
        'ie1s' => 'float',
        'ie2s' => 'float',
        'ie3s' => 'float',
        'ie4s' => 'float',
        'ieas' => 'float',
        'iebs' => 'float',
        'in0c' => 'float',
        'iscc' => 'float',
        'ip0c' => 'float',
        'icmc' => 'float',
        'ihir' => 'float',
        'ihcc' => 'float',
        'ihnc' => 'float',
        'is1c' => 'float',
        'if3c' => 'float',
        'if5c' => 'float',
        'iidc' => 'float',
        'ihsc' => 'float',
        'iulc' => 'float',
        'iurc' => 'float',
        'itpc' => 'float',
        'itar' => 'float',
        'it3c' => 'float',
        'iapc' => 'float',
        'ibtc' => 'float',
        'pb0r' => 'float',
        'pblc' => 'float',
        'pcac' => 'float',
        'pcbc' => 'float',
        'pcam' => 'float',
        'pc0c' => 'float',
        'pc1c' => 'float',
        'pc2c' => 'float',
        'pc3c' => 'float',
        'pc4c' => 'float',
        'pc5c' => 'float',
        'pc6c' => 'float',
        'pc7c' => 'float',
        'pcpd' => 'float',
        'pcpg' => 'float',
        'pcfc' => 'float',
        'pcgm' => 'float',
        'pmcc' => 'float',
        'pcpc' => 'float',
        'ptgr' => 'float',
        'pcpr' => 'float',
        'pc1r' => 'float',
        'pc5r' => 'float',
        'pcpl' => 'float',
        'pcpt' => 'float',
        'pctr' => 'float',
        'pcec' => 'float',
        'pcsc' => 'float',
        'pd0r' => 'float',
        'pg0r' => 'float',
        'pg0c' => 'float',
        'pgtr' => 'float',
        'ph1z' => 'float',
        'ph2z' => 'float',
        'ph3z' => 'float',
        'ph4z' => 'float',
        'ph02' => 'float',
        'ph05' => 'float',
        'pd2r' => 'float',
        'pp0r' => 'float',
        'pc0r' => 'float',
        'pd0r' => 'float',
        'pd5r' => 'float',
        'pdmr' => 'float',
        'pm0r' => 'float',
        'pmas' => 'float',
        'pmbs' => 'float',
        'ppsm' => 'float',
        'pm0c' => 'float',
        'pm1c' => 'float',
        'po0r' => 'float',
        'phnc' => 'float',
        'po3r' => 'float',
        'po5r' => 'float',
        'ppbr' => 'float',
        'pn1r' => 'float',
        'pn0c' => 'float',
        'pe1s' => 'float',
        'pe2s' => 'float',
        'pe3s' => 'float',
        'pe4s' => 'float',
        'peas' => 'float',
        'pebs' => 'float',
        'pp0c' => 'float',
        'ptar' => 'float',
        'ps1c' => 'float',
        'phcc' => 'float',
        'pdtr' => 'float',
        'pstr' => 'float',
        'pthc' => 'float',
        'phpc' => 'float',
        'v1r1' => 'float',
        'vacc' => 'float',
        'vv7s' => 'float',
        'vbat' => 'float',
        'vb0r' => 'float',
        'vc1c' => 'float',
        'vcs0' => 'float',
        'vcac' => 'float',
        'vcbc' => 'float',
        'vc0c' => 'float',
        'vc1c' => 'float',
        'vc2c' => 'float',
        'vc3c' => 'float',
        'vc4c' => 'float',
        'vc5c' => 'float',
        'vc6c' => 'float',
        'vc7c' => 'float',
        'vc0g' => 'float',
        'vn0c' => 'float',
        'vc0m' => 'float',
        'vs2c' => 'float',
        'vcgc' => 'float',
        'vcsc' => 'float',
        'vv1r' => 'float',
        'vcfr' => 'float',
        'vg0r' => 'float',
        'vg0c' => 'float',
        'vg1c' => 'float',
        'vg0f' => 'float',
        'vv2s' => 'float',
        'vr3r' => 'float',
        'vs8c' => 'float',
        'vh05' => 'float',
        'vv1s' => 'float',
        'vp0r' => 'float',
        'vdr2' => 'float',
        'vv9s' => 'float',
        'vd8r' => 'float',
        'vd5r' => 'float',
        'vm0r' => 'float',
        'vmas' => 'float',
        'vmbs' => 'float',
        'vn1r' => 'float',
    );

    public function __construct()
    {
        parent::__construct();
        $this->tablename = 'fan_temps';
    }

    public function up()
    {
        // Get database handle
        $dbh = $this->getdbh();

        // Wrap in transaction
        $dbh->beginTransaction();

        // Adding a column is simple...
        foreach ($this->new_columns as $column => $type) {
            $sql = "ALTER TABLE fan_temps ADD COLUMN $column $type";
            $this->exec($sql);
        }

        $dbh->commit();
    }

    public function down()
    {
        // Now that we've doubled the amount of columns, we can't go back
    }
}
