#!/bin/bash

if [ $1 = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

DIR=$(dirname $0)

echo 'Collect disk info'

mkdir -p "$DIR/cache"

# Get system disk (the one that ends with space-slash)
SYSTEM=$(df -lk | sed -n 's#^\(/dev/disk[0-9a-z]*\).* /$#\1#p')

echo "Selected system disk: ${SYSTEM}"

# Get info with diskutil
# Convert integer to string due to limitations of integer size in php
diskutil info -plist $SYSTEM | sed 's/integer>/string>/g' > "$DIR/cache/disk.plist"