#!/bin/bash

RUNTYPE="$1"
SERIAL=`ioreg -l | grep IOPlatformSerialNumber | awk '{print $4}' | tr -d '"'`
NAME="$(echo `systemsetup -getcomputername | cut -d: -f2-`)"
BASEURL="REPLACE_BASEURL"
SUBMITURL="${BASEURL}/update"

curl --max-time 5 --silent \
    -d runtype="$RUNTYPE" \
    -d serial="$SERIAL" \
    -d name="$NAME" \
    "$SUBMITURL/preflight"

exit 0
