#!/bin/bash

RUNTYPE="$1"
SERIAL=`ioreg -c IOPlatformExpertDevice | grep IOPlatformSerialNumber | awk '{print $4}' | tr -d '"'`
NAME=`scutil --get ComputerName`

BASEURL="REPLACE_BASEURL"
SUBMITURL="${BASEURL}/update"

# Application paths
CURL="/usr/bin/curl"

$CURL --max-time 5 --silent \
    -d runtype="$RUNTYPE" \
    -d serial="$SERIAL" \
    -d name="$NAME" \
    "$SUBMITURL/preflight"

exit 0
