name: build and release wip

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: ['wip']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, ldap, mysql
          coverage: xdebug
          tools: composer:v2, phpunit, phpstan
        env:
          fail-fast: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Surface PHP errors/test failures in the GitHub Actions console using matchers.
      # NOTE: No matcher required for PHPStan
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Normally, this would be composer.lock but we haven't committed that.
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev

      - name: Adjust directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # I'm not sure if this is strictly required, but it was part of the template for setup-php - m.
      - name: Clear Config Cache
        run: php please config:clear

      - name: Create ZIP archive without tests or js deps
        run: |
          zip -r munkireport-php.zip . -x node_modules/\* \*/node_modules/\* .git/\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: munkireport-php-with-deps
          path: munkireport-php.zip

      # Temporary for testing: DRAFT a release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "munkireport-php.zip"
          draft: true
          prerelease: true
          tag: wip
          commit: wip
          body: |
            This release contains artifacts that were automatically generated from an unversioned branch of MunkiReport-PHP.
            There is no guarantee that this version of MunkiReport-PHP will work at all.
          token: ${{ secrets.GITHUB_TOKEN }}
