name: build ad-hoc

on:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, ldap, mysql
          coverage: xdebug
          tools: composer:v2, phpunit, phpstan
        env:
          fail-fast: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Surface PHP errors/test failures in the GitHub Actions console using matchers.
      # NOTE: No matcher required for PHPStan
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Normally, this would be composer.lock but we haven't committed that.
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Adjust directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # I'm not sure if this is strictly required, but it was part of the template for setup-php - m.
      - name: Clear Config Cache
        run: php please config:clear

#      - name: Tar files
#        run: tar -cvf /tmp/munkireport-php.tar .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: munkireport-php-with-deps
          path: |
            .
            !tests
            !node_modules
            !build


