#!/usr/bin/python
# encoding: utf-8
'''Postflight script'''

from munkilib import munkicommon
from munkilib import reportcommon
from munkilib import FoundationPlist
import hashlib
import sys
import os

def main():
    '''Main'''
    # get runtype
    if (len(sys.argv) > 1):
        runtype = sys.argv[1]
    else:
        runtype = 'custom'
        
    # Get serial
    hardware_info = munkicommon.get_hardware_info()
    serial = hardware_info.get('serial_number', 'NO_SERIAL')
    
    items = {} # item list
    report_info = {}
    report_info['console_user'] = "%s" % munkicommon.getconsoleuser()
    report_info['runtype'] = runtype
    report_info['runstate'] = 'done'
    report_info_plist = FoundationPlist.writePlistToString(report_info)
    items = {'Reportdata':{'hash':hashlib.md5(report_info_plist).hexdigest(), \
        'data':report_info_plist}}
    
    # Read config file /Library/Preferences/Munkireport.plist
    config_items = reportcommon.pref('ReportItems') or {}
    
    for key, val in config_items.items():
        print "Requesting %s" % key 
        items[key] = {'path':val}
        
    reportcommon.process(serial, items)    

   # define path to directory with postflight scripts
    scriptdir = os.path.realpath(os.path.dirname(sys.argv[0]))
    postflightscriptdir = os.path.join(scriptdir, "postflight.d")

    if os.path.exists(postflightscriptdir):
        from munkilib import utils
        # Get all files in postflight.d
        files = os.listdir(postflightscriptdir)

        # Sort list
        files.sort()
        for postflightscript in files:
            if postflightscript.startswith('.'):
                # Skip files that start with a period
                continue
            postflightscriptpath = os.path.join(
                postflightscriptdir, postflightscript)
            if os.path.isdir(postflightscriptpath):
                # Skip directories in postflight.d directory
                continue
            try:
                # Attempt to execute script
                print 'Running %s' % postflightscript
                result, stdout, stderr = utils.runExternalScript(
                    postflightscriptpath, allow_insecure=False, script_args=[runtype])
                if stdout:
                        print(stdout.encode('UTF-8'))
                if stderr:
                    print('%s Error: %s'
                        % (postflightscript, stderr))
                if result:
                    print('postflight.d/%s return code: %d'
                                            % (postflightscript, result))
                    exit(-1)

            except utils.ScriptNotFoundError:
                pass  # Script has disappeared? Well, it is not required, so pass
            except utils.RunExternalScriptError, e:
                print >> sys.stderr, str(e)
                # Skip this script
    else:
        # /usr/local/munki/postflight.d does not exist
        pass

    exit(0)

if __name__ == '__main__':
    main()
