#!/usr/bin/python
# encoding: utf-8
'''Postflight script'''

from munkilib import munkicommon
from munkilib import reportcommon
from munkilib import FoundationPlist
import hashlib
import sys
import os

def main():
    '''Main'''
    # get runtype
    if (len(sys.argv) > 1):
        runtype = sys.argv[1]
    else:
        runtype = 'custom'

    # Try to get the munki verbosity level
    verbosity = os.environ.get('MUNKI_VERBOSITY_LEVEL')
    if (verbosity):
        reportcommon.set_verbosity(int(verbosity))
    else:
        reportcommon.set_verbosity(3)
        
    # Get serial
    hardware_info = munkicommon.get_hardware_info()
    serial = hardware_info.get('serial_number', 'NO_SERIAL')
    
    items = {} # item list
    report_info = {}
    report_info['console_user'] = "%s" % munkicommon.getconsoleuser()
    report_info['runtype'] = runtype
    report_info['runstate'] = 'done'
    report_info['uptime'] = reportcommon.get_uptime()    
    report_info_plist = FoundationPlist.writePlistToString(report_info)
    items = {'reportdata':{'hash':hashlib.md5(report_info_plist).hexdigest(), \
        'data':report_info_plist}}
    
    # Read config file /Library/Preferences/Munkireport.plist
    config_items = reportcommon.pref('ReportItems') or {}
    
    for key, val in config_items.items():
        reportcommon.display_detail("Requesting %s" % key)
        items[key] = {'path':val}
        
    reportcommon.process(serial, items)
    
    run_postflightd_scripts(runtype)

    exit(0)
    
def run_postflightd_scripts(runtype):
    # define path to directory with postflight scripts
    scriptdir = os.path.realpath(os.path.dirname(sys.argv[0]))
    postflightscriptdir = os.path.join(scriptdir, "postflight.d")

    if os.path.exists(postflightscriptdir):
        from munkilib import utils
        # Get all files in postflight.d
        files = os.listdir(postflightscriptdir)
        
        # Sort list
        files.sort()
        for postflightscript in files:
            if postflightscript.startswith('.'):
                # Skip files that start with a period
                continue
            postflightscriptpath = os.path.join(
                postflightscriptdir, postflightscript)
            if os.path.isdir(postflightscriptpath):
                # Skip directories in postflight.d directory
                continue
            try:
                # Attempt to execute script
                reportcommon.display_detail('Running %s' % postflightscript)
                result, stdout, stderr = utils.runExternalScript(
                    postflightscriptpath, allow_insecure=False, script_args=[runtype])
                if stdout:
                        reportcommon.display_detail(stdout)
                if stderr:
                    reportcommon.display_detail('%s Error: %s'
                        % (postflightscript, stderr))
                if result:
                    reportcommon.display_error('postflight.d/%s return code: %d'
                                            % (postflightscript, result))
                    continue

            except utils.ScriptNotFoundError:
                pass # Script has disappeared? Well, it is not required, so pass
            except utils.RunExternalScriptError, e:
                reportcommon.display_error( str(e) )
                # Skip this script
    else:
        # /usr/local/munki/postflight.d does not exist
        pass

if __name__ == '__main__':
    main()
