#!/bin/bash
# 
# Broken client reporter
# First argument is the message
# Second argument is the module that is reporting
# Third argument is the severity (danger, warning, info)

MSG="$1"
if [ -z "$MSG" ]; then
    MSG="Unspecified client error"
fi

# Default module is reportbrokenclient
MODULE="$2"
if [ -z "$MODULE" ]; then
    MODULE="reportbrokenclient"
fi

# Default type is danger, other possible types: warning, info
TYPE="$3"
if [ -z "$TYPE" ]; then
    TYPE="danger"
fi

SERIAL=`ioreg -c IOPlatformExpertDevice | grep IOPlatformSerialNumber | awk '{print $4}' | tr -d '"'`
NAME=`scutil --get ComputerName`

BASEURL=$(defaults read /Library/Preferences/MunkiReport BaseUrl)
PASSPHRASE=$(defaults read /Library/Preferences/MunkiReport Passphrase 2> /dev/null)
SUBMITURL="${BASEURL}/report/broken_client"

# Application paths
CURL="/usr/bin/curl"

if [[ $PASSPHRASE != "" ]] ; then

$CURL --max-time 5 --silent \
    -d msg="$MSG" \
    -d module="$MODULE" \
    -d type="$TYPE" \
    -d serial="$SERIAL" \
    -d passphrase="$PASSPHRASE" \
    -d name="$NAME" \
    "$SUBMITURL"

else

$CURL --max-time 5 --silent \
    -d msg="$MSG" \
    -d module="$MODULE" \
    -d type="$TYPE" \
    -d serial="$SERIAL" \
    -d name="$NAME" \
    "$SUBMITURL"
fi

exit 0
