#!/usr/bin/python
# encoding: utf-8

from munkilib import munkicommon
from munkilib.phpserialize import *
import subprocess
import pwd
import sys
import urllib
import urllib2
from Foundation import NSArray, NSDate, NSMetadataQuery, NSPredicate
from Foundation import CFPreferencesAppSynchronize
from Foundation import CFPreferencesCopyAppValue
from Foundation import CFPreferencesCopyKeyList
from Foundation import CFPreferencesSetValue
from Foundation import kCFPreferencesAnyUser
from Foundation import kCFPreferencesCurrentUser
from Foundation import kCFPreferencesCurrentHost
import ctypes
import struct
import time


# our preferences "bundle_id"
BUNDLE_ID = 'MunkiReport'

def curl(url, values):
    req = urllib2.Request(url, urllib.urlencode(values))
    try:
        response = urllib2.urlopen(req)
    except urllib2.URLError, e:
        if hasattr(e, 'reason'):
            print url
            print 'We failed to reach a server.'
            print 'Reason: ', e.reason
        elif hasattr(e, 'code'):
            print url
            print 'The server couldn\'t fulfill the request.'
            print 'Error code: ', e.code
        # Reportserver error, exit clean so munki keeps running
        exit(0)
    except:
        print 'A server error occurred:', sys.exc_info()[0]
        exit(0)
    return response

def get_long_username(username):
    try:
        long_name = pwd.getpwnam(username)[4]
    except:
        long_name = ''
    return long_name.decode('utf-8')
    
def get_computername():
    cmd = ['/usr/sbin/scutil', '--get', 'ComputerName']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()
    output = output.strip()
    return output.decode('utf-8')

def get_cpuinfo():
    cmd = ['/usr/sbin/sysctl', '-n', 'machdep.cpu.brand_string']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()
    output = output.strip()
    return output.decode('utf-8')

def get_uptime():
    """Returns uptime in seconds or None, on BSD (including OS X). 
    Copied from https://pypi.python.org/pypi/uptime/1.0.0"""
    try:
        libc = ctypes.CDLL('libc.dylib')
    except OSError:
        return -1
        
    if not hasattr(libc, 'sysctlbyname'):
        # Not BSD
        return -1

    # Determine how much space we need for the response
    sz = ctypes.c_uint(0)
    libc.sysctlbyname('kern.boottime', None, ctypes.byref(sz), None, 0)
    if sz.value != struct.calcsize('@LL'):
        # Unexpected, let's give up.
        return -1

    # For real now
    buf = ctypes.create_string_buffer(sz.value)
    libc.sysctlbyname('kern.boottime', buf, ctypes.byref(sz), None, 0)
    sec, usec = struct.unpack('@LL', buf.raw)
    up = int(time.time() - sec)
    return up if up > 0 else -1

def set_pref(pref_name, pref_value):
    """Sets a preference, See munkicommon.py for details"""
    CFPreferencesSetValue(
        pref_name, pref_value, BUNDLE_ID,
        kCFPreferencesAnyUser, kCFPreferencesCurrentHost)
    CFPreferencesAppSynchronize(BUNDLE_ID)
    print "set pref"
    try:
        CFPreferencesSetValue(
            pref_name, pref_value, BUNDLE_ID,
            kCFPreferencesAnyUser, kCFPreferencesCurrentHost)
        CFPreferencesAppSynchronize(BUNDLE_ID)
    except Exception:
        pass

   
def pref(pref_name):
    """Return a preference. See munkicommon.py for details
    """
    pref_value = CFPreferencesCopyAppValue(pref_name, BUNDLE_ID)
    return pref_value
    
def process(serial,items):
    """Process receives a list of items, checks if they need updating and updates them
    if necessary"""\

    # Sanitize serial
    serial = ''.join([c for c in serial if c.isalnum()])
    
    # Get prefs
    baseurl = pref('BaseUrl') or \
              munkicommon.pref('SoftwareRepoURL') + '/report/'
    
    hashurl = baseurl + "index.php?/report/hash_check"
    checkurl = baseurl + "index.php?/report/check_in"

    # Get passphrase
    passphrase = pref('Passphrase')

    # Get hashes for all scripts
    for key, i in items.items():
        if i.get('path'):
            i['hash'] = munkicommon.getmd5hash(i.get('path'))
            
    # Check dict
    check = {}
    for key, i in items.items():
        if i.get('hash'):
            check[key] = {'hash': i.get('hash')}
    
    # Send hashes to server
    values = {'serial': serial, 'items': serialize(check), 'passphrase' : passphrase}
    response = curl(hashurl, values)
    server_data = response.read();

    # Decode response
    try:
        result = unserialize(server_data)
    except:
        print 'Illegal response from the server: %s' % server_data 
        return -1
    
    if result.get('error') != '':
        print 'Server error: %s' % result['error']
        return -1

    # Retrieve hashes that need updating
    for i in items.keys():
        if i in result:
            print 'Need to update ' + i
            if items[i].get('path'):
                try:
                    f = open(items[i]['path'], "r")
                    items[i]['data'] = f.read()
                except:
                    print "ERROR: Can't open %s" % items[i]['path']
                    
        else: # delete items that don't have to be uploaded
            del items[i]

    # Send new files with hashes
    if len(items):
        print 'Sending items'
        response = curl(checkurl, {'serial': serial, 'items': serialize(items), 'passphrase': passphrase})
        print response.read()
    else:
        print 'No changes'

